[youtube]
api_key = "AIzaSyBSoIaNkweSNYh0rLXivfpFrtLF8JvUfqA"

[youtube.oauth]
# Put your client_secrets.json content here as a multiline string if needed
client_secrets = """
{
  "web": {
    "client_id": "...",
    "client_secret": "...",
    "auth_uri": "...",
    "token_uri": "...",
    "redirect_uris": ["https://<your-app>.streamlit.app/oauth2callback"]
  }
}
"""
